### ISSUE TITLE
contents of vimrc should be set by using content attribute

### ISSUE THREAD

**Issue by bahner** [ghoneycutt/puppet-module-vim#38]
As it stand ypou have to provide the vimrc from the files folder in the moudle. That's how we did back in the days :-) It should be possible to provide this from hiera or something like:

vim::root_vimrc_content: |
  :autocmd FileType make set noexpandtab
  set expandtab 
  set smarttab
  set softtabstop=2
  set tabstop=2

**Comment by bahner** [comment]
But as it stand your provided vimrc, pretty much does what I want, So I'm just gonna use that for now :-)

**Comment by ghoneycutt** [comment]
Happy to merge a PR to allow for content provided it has tests. Heh, this module was made back in those days so that the root user had a sensible vim environment and syntax for puppet.
